var icons = [ // version 2.1.6
	{ className:  'search', content: '\\f002' },
	{ className:  'mail outline', content: '\\f003' },
	{ className:  'external', content: '\\f08e' },
	{ className:  'signal', content: '\\f012' },
	{ className:  'setting', content: '\\f013' },
	{ className:  'home', content: '\\f015' },
	{ className:  'inbox', content: '\\f01c' },
	{ className:  'browser', content: '\\f022' },
	{ className:  'tag', content: '\\f02b' },
	{ className:  'tags', content: '\\f02c' },
	{ className:  'calendar', content: '\\f073' },
	{ className:  'comment', content: '\\f075' },
	{ className:  'comments', content: '\\f086' },
	{ className:  'shop', content: '\\f07a' },
	{ className:  'privacy', content: '\\f084' },
	{ className:  'settings', content: '\\f085' },
	{ className:  'trophy', content: '\\f091' },
	{ className:  'payment', content: '\\f09d' },
	{ className:  'feed', content: '\\f09e' },
	{ className:  'alarm outline', content: '\\f0a2' },
	{ className:  'tasks', content: '\\f0ae' },
	{ className:  'cloud', content: '\\f0c2' },
	{ className:  'lab', content: '\\f0c3' },
	{ className:  'mail', content: '\\f0e0' },
	{ className:  'idea', content: '\\f0eb' },
	{ className:  'dashboard', content: '\\f0e4' },
	{ className:  'sitemap', content: '\\f0e8' },
	{ className:  'alarm', content: '\\f0f3' },
	{ className:  'terminal', content: '\\f120' },
	{ className:  'code', content: '\\f121' },
	{ className:  'protect', content: '\\f132' },
	{ className:  'calendar outline', content: '\\f133' },
	{ className:  'ticket', content: '\\f145' },
	{ className:  'external square', content: '\\f14c' },
	{ className:  'map', content: '\\f14e' },
	{ className:  'bug', content: '\\f188' },
	{ className:  'mail square', content: '\\f199' },
	{ className:  'history', content: '\\f1da' },
	{ className:  'options', content: '\\f1de' },
	{ className:  'comment outline', content: '\\f0e5' },
	{ className:  'comments outline', content: '\\f0e6' },
	{ className:  'text telephone', content: '\\f1e4' },
	{ className:  'find', content: '\\f1e5' },
	{ className:  'wifi', content: '\\f1eb' },
	{ className:  'alarm slash', content: '\\f1f6' },
	{ className:  'alarm slash outline', content: '\\f1f7' },
	{ className:  'copyright', content: '\\f1f9' },
	{ className:  'at', content: '\\f1fa' },
	{ className:  'eyedropper', content: '\\f1fb' },
	{ className:  'paint brush', content: '\\f1fc' },
	{ className:  'heartbeat', content: '\\f21e' },
	{ className:  'download', content: '\\f019' },
	{ className:  'repeat', content: '\\f01e' },
	{ className:  'refresh', content: '\\f021' },
	{ className:  'lock', content: '\\f023' },
	{ className:  'bookmark', content: '\\f02e' },
	{ className:  'print', content: '\\f02f' },
	{ className:  'write', content: '\\f040' },
	{ className:  'theme', content: '\\f043' },
	{ className:  'adjust', content: '\\f042' },
	{ className:  'edit', content: '\\f044' },
	{ className:  'external share', content: '\\f045' },
	{ className:  'ban', content: '\\f05e' },
	{ className:  'mail forward', content: '\\f064' },
	{ className:  'share', content: '\\f064' },
	{ className:  'expand', content: '\\f065' },
	{ className:  'compress', content: '\\f066' },
	{ className:  'unhide', content: '\\f06e' },
	{ className:  'hide', content: '\\f070' },
	{ className:  'random', content: '\\f074' },
	{ className:  'retweet', content: '\\f079' },
	{ className:  'sign out', content: '\\f08b' },
	{ className:  'pin', content: '\\f08d' },
	{ className:  'sign in', content: '\\f090' },
	{ className:  'upload', content: '\\f093' },
	{ className:  'call', content: '\\f095' },
	{ className:  'call square', content: '\\f098' },
	{ className:  'remove bookmark', content: '\\f097' },
	{ className:  'unlock', content: '\\f09c' },
	{ className:  'configure', content: '\\f0ad' },
	{ className:  'filter', content: '\\f0b0' },
	{ className:  'wizard', content: '\\f0d0' },
	{ className:  'undo', content: '\\f0e2' },
	{ className:  'exchange', content: '\\f0ec' },
	{ className:  'cloud download', content: '\\f0ed' },
	{ className:  'cloud upload', content: '\\f0ee' },
	{ className:  'reply', content: '\\f112' },
	{ className:  'reply all', content: '\\f122' },
	{ className:  'erase', content: '\\f12d' },
	{ className:  'unlock alternate', content: '\\f13e' },
	{ className:  'archive', content: '\\f187' },
	{ className:  'translate', content: '\\f1ab' },
	{ className:  'recycle', content: '\\f1b8' },
	{ className:  'send', content: '\\f1d8' },
	{ className:  'send outline', content: '\\f1d9' },
	{ className:  'share alternate', content: '\\f1e0' },
	{ className:  'share alternate square', content: '\\f1e1' },
	{ className:  'wait', content: '\\f017' },
	{ className:  'write square', content: '\\f14b' },
	{ className:  'share square', content: '\\f14d' },
	{ className:  'add to cart', content: '\\f217' },
	{ className:  'in cart', content: '\\f218' },
	{ className:  'add user', content: '\\f234' },
	{ className:  'remove user', content: '\\f235' },
	{ className:  'help circle', content: '\\f059' },
	{ className:  'info circle', content: '\\f05a' },
	{ className:  'warning', content: '\\f12a' },
	{ className:  'warning circle', content: '\\f06a' },
	{ className:  'warning sign', content: '\\f071' },
	{ className:  'help', content: '\\f128' },
	{ className:  'info', content: '\\f129' },
	{ className:  'announcement', content: '\\f0a1' },
	{ className:  'birthday', content: '\\f1fd' },
	{ className:  'users', content: '\\f0c0' },
	{ className:  'doctor', content: '\\f0f0' },
	{ className:  'child', content: '\\f1ae' },
	{ className:  'user', content: '\\f007' },
	{ className:  'handicap', content: '\\f193' },
	{ className:  'student', content: '\\f19d' },
	{ className:  'spy', content: '\\f21b' },
	{ className:  'female', content: '\\f182' },
	{ className:  'male', content: '\\f183' },
	{ className:  'woman', content: '\\f221' },
	{ className:  'man', content: '\\f222' },
	{ className:  'non binary transgender', content: '\\f223' },
	{ className:  'intergender', content: '\\f224' },
	{ className:  'transgender', content: '\\f225' },
	{ className:  'lesbian', content: '\\f226' },
	{ className:  'gay', content: '\\f227' },
	{ className:  'heterosexual', content: '\\f228' },
	{ className:  'other gender', content: '\\f229' },
	{ className:  'other gender vertical', content: '\\f22a' },
	{ className:  'other gender horizontal', content: '\\f22b' },
	{ className:  'neuter', content: '\\f22c' },
	{ className:  'grid layout', content: '\\f00a' },
	{ className:  'list layout', content: '\\f00b' },
	{ className:  'block layout', content: '\\f009' },
	{ className:  'zoom', content: '\\f00e' },
	{ className:  'zoom out', content: '\\f010' },
	{ className:  'resize vertical', content: '\\f07d' },
	{ className:  'resize horizontal', content: '\\f07e' },
	{ className:  'maximize', content: '\\f0b2' },
	{ className:  'crop', content: '\\f125' },
	{ className:  'cocktail', content: '\\f000' },
	{ className:  'road', content: '\\f018' },
	{ className:  'flag', content: '\\f024' },
	{ className:  'book', content: '\\f02d' },
	{ className:  'gift', content: '\\f06b' },
	{ className:  'leaf', content: '\\f06c' },
	{ className:  'fire', content: '\\f06d' },
	{ className:  'plane', content: '\\f072' },
	{ className:  'magnet', content: '\\f076' },
	{ className:  'legal', content: '\\f0e3' },
	{ className:  'lemon', content: '\\f094' },
	{ className:  'world', content: '\\f0ac' },
	{ className:  'travel', content: '\\f0b1' },
	{ className:  'shipping', content: '\\f0d1' },
	{ className:  'money', content: '\\f0d6' },
	{ className:  'lightning', content: '\\f0e7' },
	{ className:  'rain', content: '\\f0e9' },
	{ className:  'treatment', content: '\\f0f1' },
	{ className:  'suitcase', content: '\\f0f2' },
	{ className:  'bar', content: '\\f0fc' },
	{ className:  'flag outline', content: '\\f11d' },
	{ className:  'flag checkered', content: '\\f11e' },
	{ className:  'puzzle', content: '\\f12e' },
	{ className:  'fire extinguisher', content: '\\f134' },
	{ className:  'rocket', content: '\\f135' },
	{ className:  'anchor', content: '\\f13d' },
	{ className:  'bullseye', content: '\\f140' },
	{ className:  'sun', content: '\\f185' },
	{ className:  'moon', content: '\\f186' },
	{ className:  'fax', content: '\\f1ac' },
	{ className:  'life ring', content: '\\f1cd' },
	{ className:  'bomb', content: '\\f1e2' },
	{ className:  'soccer', content: '\\f1e3' },
	{ className:  'calculator', content: '\\f1ec' },
	{ className:  'diamond', content: '\\f219' },
	{ className:  'crosshairs', content: '\\f05b' },
	{ className:  'asterisk', content: '\\f069' },
	{ className:  'certificate', content: '\\f0a3' },
	{ className:  'circle', content: '\\f111' },
	{ className:  'quote left', content: '\\f10d' },
	{ className:  'quote right', content: '\\f10e' },
	{ className:  'ellipsis horizontal', content: '\\f141' },
	{ className:  'ellipsis vertical', content: '\\f142' },
	{ className:  'cube', content: '\\f1b2' },
	{ className:  'cubes', content: '\\f1b3' },
	{ className:  'circle notched', content: '\\f1ce' },
	{ className:  'circle thin', content: '\\f1db' },
	{ className:  'square outline', content: '\\f096' },
	{ className:  'square', content: '\\f0c8' },
	{ className:  'checkmark', content: '\\f00c' },
	{ className:  'remove', content: '\\f00d' },
	{ className:  'checkmark box', content: '\\f046' },
	{ className:  'move', content: '\\f047' },
	{ className:  'add circle', content: '\\f055' },
	{ className:  'minus circle', content: '\\f056' },
	{ className:  'remove circle', content: '\\f057' },
	{ className:  'check circle', content: '\\f058' },
	{ className:  'remove circle outline', content: '\\f05c' },
	{ className:  'check circle outline', content: '\\f05d' },
	{ className:  'plus', content: '\\f067' },
	{ className:  'minus', content: '\\f068' },
	{ className:  'add square', content: '\\f0fe' },
	{ className:  'radio', content: '\\f10c' },
	{ className:  'selected radio', content: '\\f192' },
	{ className:  'minus square', content: '\\f146' },
	{ className:  'minus square outline', content: '\\f147' },
	{ className:  'check square', content: '\\f14a' },
	{ className:  'plus square outline', content: '\\f196' },
	{ className:  'toggle off', content: '\\f204' },
	{ className:  'toggle on', content: '\\f205' },
	{ className:  'film', content: '\\f008' },
	{ className:  'sound', content: '\\f025' },
	{ className:  'photo', content: '\\f030' },
	{ className:  'bar chart', content: '\\f080' },
	{ className:  'camera retro', content: '\\f083' },
	{ className:  'newspaper', content: '\\f1ea' },
	{ className:  'area chart', content: '\\f1fe' },
	{ className:  'pie chart', content: '\\f200' },
	{ className:  'line chart', content: '\\f201' },
	{ className:  'arrow circle outline down', content: '\\f01a' },
	{ className:  'arrow circle outline up', content: '\\f01b' },
	{ className:  'chevron left', content: '\\f053' },
	{ className:  'chevron right', content: '\\f054' },
	{ className:  'arrow left', content: '\\f060' },
	{ className:  'arrow right', content: '\\f061' },
	{ className:  'arrow up', content: '\\f062' },
	{ className:  'arrow down', content: '\\f063' },
	{ className:  'chevron up', content: '\\f077' },
	{ className:  'chevron down', content: '\\f078' },
	{ className:  'pointing right', content: '\\f0a4' },
	{ className:  'pointing left', content: '\\f0a5' },
	{ className:  'pointing up', content: '\\f0a6' },
	{ className:  'pointing down', content: '\\f0a7' },
	{ className:  'arrow circle left', content: '\\f0a8' },
	{ className:  'arrow circle right', content: '\\f0a9' },
	{ className:  'arrow circle up', content: '\\f0aa' },
	{ className:  'arrow circle down', content: '\\f0ab' },
	{ className:  'caret down', content: '\\f0d7' },
	{ className:  'caret up', content: '\\f0d8' },
	{ className:  'caret left', content: '\\f0d9' },
	{ className:  'caret right', content: '\\f0da' },
	{ className:  'angle double left', content: '\\f100' },
	{ className:  'angle double right', content: '\\f101' },
	{ className:  'angle double up', content: '\\f102' },
	{ className:  'angle double down', content: '\\f103' },
	{ className:  'angle left', content: '\\f104' },
	{ className:  'angle right', content: '\\f105' },
	{ className:  'angle up', content: '\\f106' },
	{ className:  'angle down', content: '\\f107' },
	{ className:  'chevron circle left', content: '\\f137' },
	{ className:  'chevron circle right', content: '\\f138' },
	{ className:  'chevron circle up', content: '\\f139' },
	{ className:  'chevron circle down', content: '\\f13a' },
	{ className:  'toggle down', content: '\\f150' },
	{ className:  'toggle up', content: '\\f151' },
	{ className:  'toggle right', content: '\\f152' },
	{ className:  'long arrow down', content: '\\f175' },
	{ className:  'long arrow up', content: '\\f176' },
	{ className:  'long arrow left', content: '\\f177' },
	{ className:  'long arrow right', content: '\\f178' },
	{ className:  'arrow circle outline right', content: '\\f18e' },
	{ className:  'arrow circle outline left', content: '\\f190' },
	{ className:  'toggle left', content: '\\f191' },
	{ className:  'power', content: '\\f011' },
	{ className:  'trash', content: '\\f1f8' },
	{ className:  'trash outline', content: '\\f014' },
	{ className:  'disk outline', content: '\\f0a0' },
	{ className:  'desktop', content: '\\f108' },
	{ className:  'laptop', content: '\\f109' },
	{ className:  'tablet', content: '\\f10a' },
	{ className:  'mobile', content: '\\f10b' },
	{ className:  'game', content: '\\f11b' },
	{ className:  'keyboard', content: '\\f11c' },
	{ className:  'plug', content: '\\f1e6' },
	{ className:  'folder', content: '\\f07b' },
	{ className:  'folder open', content: '\\f07c' },
	{ className:  'level up', content: '\\f148' },
	{ className:  'level down', content: '\\f149' },
	{ className:  'file', content: '\\f15b' },
	{ className:  'file outline', content: '\\f016' },
	{ className:  'file text', content: '\\f15c' },
	{ className:  'file text outline', content: '\\f0f6' },
	{ className:  'folder outline', content: '\\f114' },
	{ className:  'folder open outline', content: '\\f115' },
	{ className:  'file pdf outline', content: '\\f1c1' },
	{ className:  'file word outline', content: '\\f1c2' },
	{ className:  'file excel outline', content: '\\f1c3' },
	{ className:  'file powerpoint outline', content: '\\f1c4' },
	{ className:  'file image outline', content: '\\f1c5' },
	{ className:  'file archive outline', content: '\\f1c6' },
	{ className:  'file audio outline', content: '\\f1c7' },
	{ className:  'file video outline', content: '\\f1c8' },
	{ className:  'file code outline', content: '\\f1c9' },
	{ className:  'barcode', content: '\\f02a' },
	{ className:  'qrcode', content: '\\f029' },
	{ className:  'fork', content: '\\f126' },
	{ className:  'html5', content: '\\f13b' },
	{ className:  'css3', content: '\\f13c' },
	{ className:  'rss', content: '\\f09e' },
	{ className:  'rss square', content: '\\f143' },
	{ className:  'openid', content: '\\f19b' },
	{ className:  'database', content: '\\f1c0' },
	{ className:  'server', content: '\\f233' },
	{ className:  'heart', content: '\\f004' },
	{ className:  'star', content: '\\f005' },
	{ className:  'empty star', content: '\\f006' },
	{ className:  'thumbs outline up', content: '\\f087' },
	{ className:  'thumbs outline down', content: '\\f088' },
	{ className:  'star half', content: '\\f089' },
	{ className:  'empty heart', content: '\\f08a' },
	{ className:  'smile', content: '\\f118' },
	{ className:  'frown', content: '\\f119' },
	{ className:  'meh', content: '\\f11a' },
	{ className:  'star half empty', content: '\\f123' },
	{ className:  'thumbs up', content: '\\f164' },
	{ className:  'thumbs down', content: '\\f165' },
	{ className:  'music', content: '\\f001' },
	{ className:  'video play outline', content: '\\f01d' },
	{ className:  'volume off', content: '\\f026' },
	{ className:  'volume down', content: '\\f027' },
	{ className:  'volume up', content: '\\f028' },
	{ className:  'record', content: '\\f03d' },
	{ className:  'step backward', content: '\\f048' },
	{ className:  'fast backward', content: '\\f049' },
	{ className:  'backward', content: '\\f04a' },
	{ className:  'play', content: '\\f04b' },
	{ className:  'pause', content: '\\f04c' },
	{ className:  'stop', content: '\\f04d' },
	{ className:  'forward', content: '\\f04e' },
	{ className:  'fast forward', content: '\\f050' },
	{ className:  'step forward', content: '\\f051' },
	{ className:  'eject', content: '\\f052' },
	{ className:  'unmute', content: '\\f130' },
	{ className:  'mute', content: '\\f131' },
	{ className:  'video play', content: '\\f144' },
	{ className:  'closed captioning', content: '\\f20a' },
	{ className:  'marker', content: '\\f041' },
	{ className:  'coffee', content: '\\f0f4' },
	{ className:  'food', content: '\\f0f5' },
	{ className:  'building outline', content: '\\f0f7' },
	{ className:  'hospital', content: '\\f0f8' },
	{ className:  'emergency', content: '\\f0f9' },
	{ className:  'first aid', content: '\\f0fa' },
	{ className:  'military', content: '\\f0fb' },
	{ className:  'h', content: '\\f0fd' },
	{ className:  'location arrow', content: '\\f124' },
	{ className:  'space shuttle', content: '\\f197' },
	{ className:  'university', content: '\\f19c' },
	{ className:  'building', content: '\\f1ad' },
	{ className:  'paw', content: '\\f1b0' },
	{ className:  'spoon', content: '\\f1b1' },
	{ className:  'car', content: '\\f1b9' },
	{ className:  'taxi', content: '\\f1ba' },
	{ className:  'tree', content: '\\f1bb' },
	{ className:  'bicycle', content: '\\f206' },
	{ className:  'bus', content: '\\f207' },
	{ className:  'ship', content: '\\f21a' },
	{ className:  'motorcycle', content: '\\f21c' },
	{ className:  'street view', content: '\\f21d' },
	{ className:  'hotel', content: '\\f236' },
	{ className:  'train', content: '\\f238' },
	{ className:  'subway', content: '\\f239' },
	{ className:  'table', content: '\\f0ce' },
	{ className:  'columns', content: '\\f0db' },
	{ className:  'sort', content: '\\f0dc' },
	{ className:  'sort ascending', content: '\\f0de' },
	{ className:  'sort descending', content: '\\f0dd' },
	{ className:  'sort alphabet ascending', content: '\\f15d' },
	{ className:  'sort alphabet descending', content: '\\f15e' },
	{ className:  'sort content ascending', content: '\\f160' },
	{ className:  'sort content descending', content: '\\f161' },
	{ className:  'sort numeric ascending', content: '\\f162' },
	{ className:  'sort numeric descending', content: '\\f163' },
	{ className:  'font', content: '\\f031' },
	{ className:  'bold', content: '\\f032' },
	{ className:  'italic', content: '\\f033' },
	{ className:  'text height', content: '\\f034' },
	{ className:  'text width', content: '\\f035' },
	{ className:  'align left', content: '\\f036' },
	{ className:  'align center', content: '\\f037' },
	{ className:  'align right', content: '\\f038' },
	{ className:  'align justify', content: '\\f039' },
	{ className:  'list', content: '\\f03a' },
	{ className:  'outdent', content: '\\f03b' },
	{ className:  'indent', content: '\\f03c' },
	{ className:  'linkify', content: '\\f0c1' },
	{ className:  'cut', content: '\\f0c4' },
	{ className:  'copy', content: '\\f0c5' },
	{ className:  'attach', content: '\\f0c6' },
	{ className:  'save', content: '\\f0c7' },
	{ className:  'content', content: '\\f0c9' },
	{ className:  'unordered list', content: '\\f0ca' },
	{ className:  'ordered list', content: '\\f0cb' },
	{ className:  'strikethrough', content: '\\f0cc' },
	{ className:  'underline', content: '\\f0cd' },
	{ className:  'paste', content: '\\f0ea' },
	{ className:  'unlink', content: '\\f127' },
	{ className:  'superscript', content: '\\f12b' },
	{ className:  'subscript', content: '\\f12c' },
	{ className:  'header', content: '\\f1dc' },
	{ className:  'paragraph', content: '\\f1dd' },
	{ className:  'euro', content: '\\f153' },
	{ className:  'pound', content: '\\f154' },
	{ className:  'dollar', content: '\\f155' },
	{ className:  'rupee', content: '\\f156' },
	{ className:  'yen', content: '\\f157' },
	{ className:  'ruble', content: '\\f158' },
	{ className:  'won', content: '\\f159' },
	{ className:  'lira', content: '\\f195' },
	{ className:  'shekel', content: '\\f20b' },
	{ className:  'paypal', content: '\\f1ed' },
	{ className:  'paypal card', content: '\\f1f4' },
	{ className:  'google wallet', content: '\\f1ee' },
	{ className:  'visa', content: '\\f1f0' },
	{ className:  'mastercard', content: '\\f1f1' },
	{ className:  'discover', content: '\\f1f2' },
	{ className:  'american express', content: '\\f1f3' },
	{ className:  'stripe', content: '\\f1f5' },
	{ className:  'twitter square', content: '\\f081' },
	{ className:  'facebook square', content: '\\f082' },
	{ className:  'linkedin square', content: '\\f08c' },
	{ className:  'github square', content: '\\f092' },
	{ className:  'twitter', content: '\\f099' },
	{ className:  'facebook', content: '\\f09a' },
	{ className:  'github', content: '\\f09b' },
	{ className:  'pinterest', content: '\\f0d2' },
	{ className:  'pinterest square', content: '\\f0d3' },
	{ className:  'google plus square', content: '\\f0d4' },
	{ className:  'google plus', content: '\\f0d5' },
	{ className:  'linkedin', content: '\\f0e1' },
	{ className:  'github alternate', content: '\\f113' },
	{ className:  'maxcdn', content: '\\f136' },
	{ className:  'bitcoin', content: '\\f15a' },
	{ className:  'youtube square', content: '\\f166' },
	{ className:  'youtube', content: '\\f167' },
	{ className:  'xing', content: '\\f168' },
	{ className:  'xing square', content: '\\f169' },
	{ className:  'youtube play', content: '\\f16a' },
	{ className:  'dropbox', content: '\\f16b' },
	{ className:  'stack overflow', content: '\\f16c' },
	{ className:  'instagram', content: '\\f16d' },
	{ className:  'flickr', content: '\\f16e' },
	{ className:  'adn', content: '\\f170' },
	{ className:  'bitbucket', content: '\\f171' },
	{ className:  'bitbucket square', content: '\\f172' },
	{ className:  'tumblr', content: '\\f173' },
	{ className:  'tumblr square', content: '\\f174' },
	{ className:  'apple', content: '\\f179' },
	{ className:  'windows', content: '\\f17a' },
	{ className:  'android', content: '\\f17b' },
	{ className:  'linux', content: '\\f17c' },
	{ className:  'dribbble', content: '\\f17d' },
	{ className:  'skype', content: '\\f17e' },
	{ className:  'foursquare', content: '\\f180' },
	{ className:  'trello', content: '\\f181' },
	{ className:  'gittip', content: '\\f184' },
	{ className:  'vk', content: '\\f189' },
	{ className:  'weibo', content: '\\f18a' },
	{ className:  'renren', content: '\\f18b' },
	{ className:  'pagelines', content: '\\f18c' },
	{ className:  'stack exchange', content: '\\f18d' },
	{ className:  'vimeo', content: '\\f194' },
	{ className:  'slack', content: '\\f198' },
	{ className:  'wordpress', content: '\\f19a' },
	{ className:  'yahoo', content: '\\f19e' },
	{ className:  'google', content: '\\f1a0' },
	{ className:  'reddit', content: '\\f1a1' },
	{ className:  'reddit square', content: '\\f1a2' },
	{ className:  'stumbleupon circle', content: '\\f1a3' },
	{ className:  'stumbleupon', content: '\\f1a4' },
	{ className:  'delicious', content: '\\f1a5' },
	{ className:  'digg', content: '\\f1a6' },
	{ className:  'pied piper', content: '\\f1a7' },
	{ className:  'pied piper alternate', content: '\\f1a8' },
	{ className:  'drupal', content: '\\f1a9' },
	{ className:  'joomla', content: '\\f1aa' },
	{ className:  'behance', content: '\\f1b4' },
	{ className:  'behance square', content: '\\f1b5' },
	{ className:  'steam', content: '\\f1b6' },
	{ className:  'steam square', content: '\\f1b7' },
	{ className:  'spotify', content: '\\f1bc' },
	{ className:  'deviantart', content: '\\f1bd' },
	{ className:  'soundcloud', content: '\\f1be' },
	{ className:  'vine', content: '\\f1ca' },
	{ className:  'codepen', content: '\\f1cb' },
	{ className:  'jsfiddle', content: '\\f1cc' },
	{ className:  'rebel', content: '\\f1d0' },
	{ className:  'empire', content: '\\f1d1' },
	{ className:  'git square', content: '\\f1d2' },
	{ className:  'git', content: '\\f1d3' },
	{ className:  'hacker news', content: '\\f1d4' },
	{ className:  'tencent weibo', content: '\\f1d5' },
	{ className:  'qq', content: '\\f1d6' },
	{ className:  'wechat', content: '\\f1d7' },
	{ className:  'slideshare', content: '\\f1e7' },
	{ className:  'twitch', content: '\\f1e8' },
	{ className:  'yelp', content: '\\f1e9' },
	{ className:  'lastfm', content: '\\f202' },
	{ className:  'lastfm square', content: '\\f203' },
	{ className:  'ioxhost', content: '\\f208' },
	{ className:  'angellist', content: '\\f209' },
	{ className:  'meanpath', content: '\\f20c' },
	{ className:  'buysellads', content: '\\f20d' },
	{ className:  'connectdevelop', content: '\\f20e' },
	{ className:  'dashcube', content: '\\f210' },
	{ className:  'forumbee', content: '\\f211' },
	{ className:  'leanpub', content: '\\f212' },
	{ className:  'sellsy', content: '\\f213' },
	{ className:  'shirtsinbulk', content: '\\f214' },
	{ className:  'simplybuilt', content: '\\f215' },
	{ className:  'skyatlas', content: '\\f216' },
	{ className:  'whatsapp', content: '\\f232' },
	{ className:  'viacoin', content: '\\f237' },
	{ className:  'medium', content: '\\f23a' },
	{ className:  'like', content: '\\f004' },
	{ className:  'favorite', content: '\\f005' },
	{ className:  'video', content: '\\f008' },
	{ className:  'check', content: '\\f00c' },
	{ className:  'close', content: '\\f00d' },
	{ className:  'cancel', content: '\\f00d' },
	{ className:  'delete', content: '\\f00d' },
	{ className:  'x', content: '\\f00d' },
	{ className:  'user times', content: '\\f235' },
	{ className:  'user close', content: '\\f235' },
	{ className:  'user cancel', content: '\\f235' },
	{ className:  'user delete', content: '\\f235' },
	{ className:  'user x', content: '\\f235' },
	{ className:  'zoom in', content: '\\f00e' },
	{ className:  'magnify', content: '\\f00e' },
	{ className:  'shutdown', content: '\\f011' },
	{ className:  'clock', content: '\\f017' },
	{ className:  'time', content: '\\f017' },
	{ className:  'play circle outline', content: '\\f01d' },
	{ className:  'headphone', content: '\\f025' },
	{ className:  'camera', content: '\\f030' },
	{ className:  'video camera', content: '\\f03d' },
	{ className:  'picture', content: '\\f03e' },
	{ className:  'pencil', content: '\\f040' },
	{ className:  'compose', content: '\\f040' },
	{ className:  'point', content: '\\f041' },
	{ className:  'tint', content: '\\f043' },
	{ className:  'signup', content: '\\f044' },
	{ className:  'plus circle', content: '\\f055' },
	{ className:  'dont', content: '\\f05e' },
	{ className:  'minimize', content: '\\f066' },
	{ className:  'add', content: '\\f067' },
	{ className:  'eye', content: '\\f06e' },
	{ className:  'attention', content: '\\f06a' },
	{ className:  'cart', content: '\\f07a' },
	{ className:  'shuffle', content: '\\f074' },
	{ className:  'talk', content: '\\f075' },
	{ className:  'chat', content: '\\f075' },
	{ className:  'shopping cart', content: '\\f07a' },
	{ className:  'bar graph', content: '\\f080' },
	{ className:  'area graph', content: '\\f1fe' },
	{ className:  'pie graph', content: '\\f200' },
	{ className:  'line graph', content: '\\f201' },
	{ className:  'key', content: '\\f084' },
	{ className:  'cogs', content: '\\f085' },
	{ className:  'discussions', content: '\\f086' },
	{ className:  'like outline', content: '\\f087' },
	{ className:  'dislike outline', content: '\\f088' },
	{ className:  'heart outline', content: '\\f08a' },
	{ className:  'log out', content: '\\f08b' },
	{ className:  'thumb tack', content: '\\f08d' },
	{ className:  'winner', content: '\\f091' },
	{ className:  'bookmark outline', content: '\\f097' },
	{ className:  'phone', content: '\\f095' },
	{ className:  'phone square', content: '\\f098' },
	{ className:  'credit card', content: '\\f09d' },
	{ className:  'hdd outline', content: '\\f0a0' },
	{ className:  'bullhorn', content: '\\f0a1' },
	{ className:  'bell', content: '\\f0f3' },
	{ className:  'bell outline', content: '\\f0a2' },
	{ className:  'bell slash', content: '\\f1f6' },
	{ className:  'bell slash outline', content: '\\f1f7' },
	{ className:  'hand outline right', content: '\\f0a4' },
	{ className:  'hand outline left', content: '\\f0a5' },
	{ className:  'hand outline up', content: '\\f0a6' },
	{ className:  'hand outline down', content: '\\f0a7' },
	{ className:  'globe', content: '\\f0ac' },
	{ className:  'wrench', content: '\\f0ad' },
	{ className:  'briefcase', content: '\\f0b1' },
	{ className:  'group', content: '\\f0c0' },
	{ className:  'flask', content: '\\f0c3' },
	{ className:  'sidebar', content: '\\f0c9' },
	{ className:  'bars', content: '\\f0c9' },
	{ className:  'list ul', content: '\\f0ca' },
	{ className:  'list ol', content: '\\f0cb' },
	{ className:  'numbered list', content: '\\f0cb' },
	{ className:  'magic', content: '\\f0d0' },
	{ className:  'truck', content: '\\f0d1' },
	{ className:  'currency', content: '\\f0d6' },
	{ className:  'triangle down', content: '\\f0d7' },
	{ className:  'dropdown', content: '\\f0d7' },
	{ className:  'triangle up', content: '\\f0d8' },
	{ className:  'triangle left', content: '\\f0d9' },
	{ className:  'triangle right', content: '\\f0da' },
	{ className:  'envelope', content: '\\f0e0' },
	{ className:  'conversation', content: '\\f0e6' },
	{ className:  'umbrella', content: '\\f0e9' },
	{ className:  'clipboard', content: '\\f0ea' },
	{ className:  'lightbulb', content: '\\f0eb' },
	{ className:  'ambulance', content: '\\f0f9' },
	{ className:  'medkit', content: '\\f0fa' },
	{ className:  'fighter jet', content: '\\f0fb' },
	{ className:  'beer', content: '\\f0fc' },
	{ className:  'plus square', content: '\\f0fe' },
	{ className:  'computer', content: '\\f108' },
	{ className:  'circle outline', content: '\\f10c' },
	{ className:  'intersex', content: '\\f10c' },
	{ className:  'asexual', content: '\\f10c' },
	{ className:  'spinner', content: '\\f110' },
	{ className:  'gamepad', content: '\\f11b' },
	{ className:  'star half full', content: '\\f123' },
	{ className:  'question', content: '\\f128' },
	{ className:  'eraser', content: '\\f12d' },
	{ className:  'microphone', content: '\\f130' },
	{ className:  'microphone slash', content: '\\f131' },
	{ className:  'shield', content: '\\f132' },
	{ className:  'target', content: '\\f140' },
	{ className:  'play circle', content: '\\f144' },
	{ className:  'pencil square', content: '\\f14b' },
	{ className:  'compass', content: '\\f14e' },
	{ className:  'amex', content: '\\f1f3' },
	{ className:  'eur', content: '\\f153' },
	{ className:  'gbp', content: '\\f154' },
	{ className:  'usd', content: '\\f155' },
	{ className:  'inr', content: '\\f156' },
	{ className:  'cny', content: '\\f157' },
	{ className:  'rmb', content: '\\f157' },
	{ className:  'jpy', content: '\\f157' },
	{ className:  'rouble', content: '\\f158' },
	{ className:  'rub', content: '\\f158' },
	{ className:  'krw', content: '\\f159' },
	{ className:  'btc', content: '\\f15a' },
	{ className:  'sheqel', content: '\\f20b' },
	{ className:  'ils', content: '\\f20b' },
	{ className:  'try', content: '\\f195' },
	{ className:  'zip', content: '\\f187' },
	{ className:  'dot circle outline', content: '\\f192' },
	{ className:  'sliders', content: '\\f1de' },
	{ className:  'wi-fi', content: '\\f1eb' },
	{ className:  'graduation', content: '\\f19d' },
	{ className:  'weixin', content: '\\f1d7' },
	{ className:  'binoculars', content: '\\f1e5' },
	{ className:  'gratipay', content: '\\f184' },
	{ className:  'genderless', content: '\\f1db' },
	{ className:  'teletype', content: '\\f1e4' },
	{ className:  'power cord', content: '\\f1e6' },
	{ className:  'tty', content: '\\f1e4' },
	{ className:  'cc', content: '\\f20a' },
	{ className:  'plus cart', content: '\\f217' },
	{ className:  'arrow down cart', content: '\\f218' },
	{ className:  'detective', content: '\\f21b' },
	{ className:  'venus', content: '\\f221' },
	{ className:  'mars', content: '\\f222' },
	{ className:  'mercury', content: '\\f223' },
	{ className:  'venus double', content: '\\f226' },
	{ className:  'female homosexual', content: '\\f226' },
	{ className:  'mars double', content: '\\f227' },
	{ className:  'male homosexual', content: '\\f227' },
	{ className:  'venus mars', content: '\\f228' },
	{ className:  'mars stroke', content: '\\f229' },
	{ className:  'mars alternate', content: '\\f229' },
	{ className:  'mars vertical', content: '\\f22a' },
	{ className:  'mars horizontal', content: '\\f22b' },
	{ className:  'mars stroke vertical', content: '\\f22a' },
	{ className:  'mars stroke horizontal', content: '\\f22b' },
	{ className:  'facebook official', content: '\\f230' },
	{ className:  'pinterest official', content: '\\f231' },
	{ className:  'bed', content: '\\f236' }
];

$.expr[':'].icon = function(a,i,m){
  return (a.getAttribute('data-icon') ||  '').toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
};
var $container = $('#container');
$.each(icons, function(i, v) {
  var html = [
  '<i class="' + v.className + ' icon"></i>',
  '<div>' + v.className + '<span>',
  '<i class="tiny angle left icon"></i>',
  v.content,
  '<i class="tiny angle right icon"></i>',
  '</span>',
  '</div>',
  '</li>'];
  $('<li></li>')
    .attr('data-icon', v.className)
    .html(html.join(''))
    .appendTo($container);
});
var $search = $('#search');
$search.on('keyup', function () {
  var filter = $(this).val();
  if (filter) {
    var $matches = $($container).find('li:icon(' + filter + ')');
    $('li', $container).not($matches).hide();
    $matches.show();
  }
  else {
    $('li', $container).show();
  }

  return false;
});
